### ISSUE TITLE
Issue with activity being recreated when receiving file upload result

### ISSUE THREAD

**Issue by dzolnai** [delight-im/Android-AdvancedWebView#15]
At a small number of users I noticed that the system has to recreate the activity before delivering the result through `onActivityResult(...)`. This means that also a new `AdvancedWebView` will be created, which won't have the same `mFileUploadCallbacks` as the original one. Is there a way to persist these, that the WebView could receive them even if it gets recreated?

**Comment by mwaclawek** [comment]
Thanks for pointing this out!

You can always persist such instances by storing the reference in your `Application` class that will only be destroyed if your whole app/process will be destroyed.

Apart from that, it might be sufficient to make the two members `mFileUploadCallbackFirst` and `mFileUploadCallbackSecond` static in `AdvancedWebView`. Could you try this?

If you can reproduce the behaviour of the `Activity` being destroyed before the result is delivered, you could test this -- and if it works, we'll adopt the change here.

The only downside would be that you won't be able to have pending results in *two* `Activity` instances at the same time. Say you call `startActivityForResult(...)` in one `Activity` which opens another app. Then you pause this app and open a new `Activity` in your app. There, you call `startActivityForResult(...)` again. Now you're waiting for *two* pending results but you will never be able to receive the first one because the second `Activity` has now overwritten the callback.

But I don't think this will happen, usually.

**Comment by dzolnai** [comment]
Good idea with the static variables. I can't think of a use-case, where there could be two different pending upload callbacks (at least in my app), so I'll make this change in our product. I'll come back within a month when I can verify if this solution worked.

**Comment by mwaclawek** [comment]
Thanks, that would be great!

If it worked, we'll definitely adopt the fix here :)

**Comment by dzolnai** [comment]
*Update:* I deployed the fix (making the callbacks static), and issued an application update 2 weeks ago. We didn't have crashes since then with this issue, so indeed it is a viable solution.
I also had to make the `onActivityResult(...)` method static, because it accesses static variables.

**Comment by mwaclawek** [comment]
Thank you so much!

Good to hear that it worked. A few questions are still open, however. Could you help?

 1. When the `AdvancedWebView` is re-created because the containing `Activity` is re-created, is the file upload callback useful anymore? The `WebView`will go back to the start page, not the last page you were on and neither the last state and position you were in, right? Where will the selected file go to?
 2. Making `onActivityResult(...)` static shouldn't be necessary, as non-static methods can access static fields just fine. Only the other way round doesn't work.
 3. Did you collect crash data with the Google Play Developer Console (where users report just 5% of crashes or less) or did you use a dedicated crash reporting service such as ACRA, Crashlytics etc. (where almost all crashes end up being reported)? If you use the first option, the crashes may still occur but just have been missed, right?

**Comment by dzolnai** [comment]
1. I'm not really sure. We used restoring the instance state of the WebView in the application though, so the page would not be reset in this case. However it does still count for a page refresh. I don't know how the upload callbacks treat a page refresh like this.
2. Right, now I remember why I made them static: the WebView was inside a fragment, and when the activity recreated itself, the fragment view was not done yet. So I could not get a reference to the WebView, instead I made the method static, since it only accesses static fields.
3. I collected the data using Crashlytics. The crash occurred 23 times in total, over the course of approx. 2 weeks. I just checked, and the crash didn't reoccur since March 31. The number of users also increased since.

Sorry for the late answer :)

**Comment by mwaclawek** [comment]
Okay, thanks for the clarification :)

Last thing (Promise!), could you somehow look up that old exception again? It would be useful to know what type of exception this was or in which lines it was caused. Of course, you can leave out all the lines from the stack trace that affect your private code.

Assuming the `Activity` (and thus the `WebView`) is re-created, a `NullPointerException` is the most likely candidate for a crash. However, in `onActivityResult(...)`, every variable is checked explicitly, so it's not clear how an exception could be thrown there.

Thank you :)

**Comment by dzolnai** [comment]
Yes it was a NullPointerException because the WebView reference got nulled while the activity was re-created. 

The stack trace was (replaced package name):
```
java.lang.RuntimeException: Unable to resume activity {com.example.app/com.example.app.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1000, result=-1, data=Intent { dat=content://media/external/images/media/527997 typ=image/jpeg (has extras) }} to activity {com.example.app/com.example.app.MainActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2812)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2851)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2234)
       at android.app.ActivityThread.access$600(ActivityThread.java:139)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1261)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:4944)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1000, result=-1, data=Intent { dat=content://media/external/images/media/527997 typ=image/jpeg (has extras) }} to activity {com.example.app/com.example.app.MainActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3387)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2793)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2851)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2234)
       at android.app.ActivityThread.access$600(ActivityThread.java:139)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1261)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:4944)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.NullPointerException
       at com.example.app.WebAppFragment.deliverResult(WebAppFragment.java:57)
       at com.example.app.MainActivity.onActivityResult(MainActivity.java:121)
       at android.app.Activity.dispatchActivityResult(Activity.java:4740)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3383)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2793)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2851)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2234)
       at android.app.ActivityThread.access$600(ActivityThread.java:139)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1261)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:4944)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by mwaclawek** [comment]
Thank you!

Well, from these two lines, it seems the issue was in your own code. Could that actually be the case?

```
Caused by: java.lang.NullPointerException
       at com.example.app.WebAppFragment.deliverResult(WebAppFragment.java:57)
       at com.example.app.MainActivity.onActivityResult(MainActivity.java:121)
```

The two classes `MainActivity` and `WebAppFragment` are two of your own components extending `Activity` and `Fragment`, right?

So `MainActivity.java:121` probably calls `WebAppFragment`. And in `WebAppFragment.java:57`, what is there, or rather, was there (at the time of the error)? Any chance you can look this up?

Because from that code, it seems that your own class `WebAppFragment` has a `NullPointerException` in method `deliverResult(...)` and more specifically on line `57`.

The `AdvancedWebView.java` class is not mentioned anywhere, it seems.
