### ISSUE TITLE
File Input Crashes using API SDK 23

### ISSUE THREAD

**Issue by steventnorris-40AU** [delight-im/Android-AdvancedWebView#185]
When using API SDK 23, a crash occurs after the callback from a file selection using a file input.

Logs below:

```
03-15 20:16:53.796 4648-4711/com.fortyau.backpack D/EGL_emulation: eglMakeCurrent: 0xaa099100: ver 3 0 (tinfo 0xaa3fa7b0)
03-15 20:16:53.799 4648-4711/com.fortyau.backpack E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb403d660
03-15 20:16:57.711 4648-4742/com.fortyau.backpack E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
                                                                    Process: com.fortyau.backpack, PID: 4648
                                                                    java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                        at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                        at java.lang.Thread.run(Thread.java:818)
                                                                     Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media/35 from pid=4648, uid=10061 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
                                                                        at android.os.Parcel.readException(Parcel.java:1599)
                                                                        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
                                                                        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
                                                                        at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
                                                                        at android.content.ContentResolver.query(ContentResolver.java:491)
                                                                        at android.content.ContentResolver.query(ContentResolver.java:434)
                                                                        at org.chromium.base.ContentUriUtils.getDisplayName(ContentUriUtils.java:134)
                                                                        at org.chromium.android_webview.AwWebContentsDelegateAdapter$GetDisplayNameTask.resolveFileName(AwWebContentsDelegateAdapter.java:308)
                                                                        at org.chromium.android_webview.AwWebContentsDelegateAdapter$GetDisplayNameTask.doInBackground(AwWebContentsDelegateAdapter.java:291)
                                                                        at org.chromium.android_webview.AwWebContentsDelegateAdapter$GetDisplayNameTask.doInBackground(AwWebContentsDelegateAdapter.java:271)
                                                                        at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                        at java.lang.Thread.run(Thread.java:818) 
03-15 20:16:57.769 4648-4711/com.fortyau.backpack D/EGL_emulation: eglMakeCurrent: 0xaa099100: ver 3 0 (tinfo 0xaa3fa7b0)
03-15 20:16:57.804 4648-4711/com.fortyau.backpack E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
03-15 20:16:57.927 4648-4711/com.fortyau.backpack E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
03-15 20:16:57.996 4648-4711/com.fortyau.backpack E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
03-15 20:16:58.049 4648-4711/com.fortyau.backpack E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
03-15 20:16:58.075 4648-4711/com.fortyau.backpack E/eglCodecCommon: glUtilsParamSize: unknow param 0x000085b5
```

**Comment by ocram** [comment]
You should indeed make sure *in your own application code* that the user grants either

```
android.permission.READ_EXTERNAL_STORAGE
```

or even

```
android.permission.WRITE_EXTERNAL_STORAGE
```

so that files can be read and thus uploaded.

But I guess you’re suggesting that users may reasonably deny this permission (while still accepting others) and this library should handle this better.

What do you suggest we do instead? I think we should call a new internal callback `onStorageReadAccess` that returns `true` by default (which means that access is allowed) and which you could override to return `false` instead (which means that access is forbidden). You could return a dynamic response and launch your own dialogs and permission requests.

**Comment by steventnorris-40AU** [comment]
I think you could take that one step further and have an internal method, overridable, 'permissionCheck(int for)' that could be used for any method that may require permissions and is given an subset of static ints indicating GPS_REQUEST, FILE_INPUT, etc. I noticed you include some GPS methods. I haven't used them, but I imagine they could face the same issue.

Sidenote, also noticed the intent for the fileinput was just a file selector. I'll need to add the ability in the near future for that to be a selection between taking a picture with camera or selecting a file from the file explorer. If you do expand the functionality of the file input methods, might make a few of those overridable for custom file handling. I'd assume that would just be the onFileInput and the activity callbacks

**Comment by Miha-x64** [comment]
On which device this error occurs?
I have a similar bug report, but can't reproduce the issue. Some custom ROMs seem not to grant required Uri permission.
