### ISSUE TITLE
Phone Model: Galaxy J3 Pro Android System Version: 7.0 Error: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed

### ISSUE THREAD

**Issue by rgdzh1** [delight-im/Android-AdvancedWebView#197]
android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
        at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:270)
        at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:330)
        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:194)
        at android.webkit.WebView.getFactory(WebView.java:2325)
        at android.webkit.WebView.ensureProviderCreated(WebView.java:2320)
        at android.webkit.WebView.setOverScrollMode(WebView.java:2379)
        at android.view.View.<init>(View.java:4331)
        at android.view.View.<init>(View.java:4473)
        at android.view.ViewGroup.<init>(ViewGroup.java:579)
        at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
        at android.webkit.WebView.<init>(WebView.java:627)
        at android.webkit.WebView.<init>(WebView.java:572)
        at android.webkit.WebView.<init>(WebView.java:555)
        at android.webkit.WebView.<init>(WebView.java:542)
        at im.delight.android.webview.AdvancedWebView.<init>(Unknown Source)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at android.view.LayoutInflater.createView(LayoutInflater.java:652)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:794)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:873)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:378)
        at oklik.flb.jkcash.com.ui.base.BaseActivity.createView(Unknown Source)
        at oklik.flb.jkcash.com.ui.base.BaseActivity.onCreate(Unknown Source)
        at android.app.Activity.performCreate(Activity.java:6958)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
        at android.app.ActivityThread.-wrap14(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

**Comment by ocram** [comment]
Please make sure [Google Chrome](https://play.google.com/store/apps/details?id=com.android.chrome) or [Android System WebView](https://play.google.com/store/apps/details?id=com.google.android.webview) is installed on the device.

**Comment by ankitgupta199** [comment]
I am also getting same exception for android 7 (Naugat) on some random devices, want to know is there any way I can handle this exception, so that I can show users any message to install Android System WebView and chrome without crash app. Because main issue is this I am not able to reproduce same exception on my available devices or emulators and this error is coming in layout binding method onCreateView, from here it crashes.
`@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
       return inflater.inflate(R.layout.fragment_webview, false);  // _no webview installed exception here, it crash app_
    }`
