### ISSUE TITLE
App crash on clicking select box in webview in android 22

### ISSUE THREAD

**Issue by biancaarno8** [delight-im/Android-AdvancedWebView#256]
Hi, when i try to open a popup window (or select box) in webview, the app crashes.
The message is:
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:566)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:282)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
        at android.app.Dialog.show(Dialog.java:298)
        at com.android.org.chromium.content.browser.input.SelectPopupDialog.show(SelectPopupDialog.java:133)
        at com.android.org.chromium.content.browser.ContentViewCore.showSelectPopup(ContentViewCore.java:2229)
W/System.err:     at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
        at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

Any solution??

**Comment by awisalkarni** [comment]
You can try using YourActivity.this instead of this.

**Comment by biancaarno8** [comment]
hello, thanks for the reply, but the problem was with the appcompact library, after updating it to the latest version, they solved the problem
