### ISSUE TITLE
blob:// pdf not downloading please help

### ISSUE THREAD

**Issue by tsquaredesigns** [delight-im/Android-AdvancedWebView#267]

**Comment by Kazi-paywell** [comment]
Process: com.journaldev.webview, PID: 5008
    android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=blob:https://www.app.landknock.com/fdeea869-b145-4264-bf3e-a8cad8ea8b50 flg=0x10000000 (has extras) }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2058)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
        at android.app.ContextImpl.startActivity(ContextImpl.java:985)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:416)
        at androidx.core.content.ContextCompat.startActivity(ContextCompat.java:251)
        at androidx.browser.customtabs.CustomTabsIntent.launchUrl(CustomTabsIntent.java:376)
        at com.journaldev.webview.MainActivity$1.onDownloadStart(MainActivity.java:112)
        at r8.handleMessage(chromium-TrichromeWebViewGoogle.aab-stable-443021033:145)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7824)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:512)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1027)

**Comment by ocram** [comment]
Unfortunately, there is no native support for `blob` downloads, but only for downloads via URLs to resources stored on a the server. That means there is no easy solution here, either. Sorry!

Please try Android’s `JavascriptInterface` or JavaScript’s `XMLHttpRequest` to fetch and convert the `blob`.
